"""Small, optional Ollama client for selecting validated dictionary candidates."""

from __future__ import annotations

import base64
import json
from typing import Sequence
from urllib.error import HTTPError, URLError
from urllib.parse import urlparse
from urllib.request import Request, urlopen

from .codec import Candidate


class OllamaError(RuntimeError):
    pass


def _validate_local_url(url: str) -> None:
    parsed_url = urlparse(url)
    if parsed_url.scheme not in ("http", "https") or parsed_url.hostname not in (
        "127.0.0.1",
        "localhost",
        "::1",
    ):
        raise OllamaError("Ollama URL must point to localhost")


def list_models(
    *, url: str = "http://127.0.0.1:11434", timeout: float = 5.0
) -> list[str]:
    """Return model names installed in the local Ollama instance."""
    _validate_local_url(url)
    request = Request(url.rstrip("/") + "/api/tags", method="GET")
    try:
        with urlopen(request, timeout=timeout) as response:
            payload = json.loads(response.read())
    except (HTTPError, URLError, TimeoutError, json.JSONDecodeError, OSError) as exc:
        raise OllamaError(f"Ollama model lookup failed: {exc}") from exc
    models = payload.get("models", [])
    if not isinstance(models, list):
        raise OllamaError("Ollama returned an invalid model list")
    names = {
        item.get("name")
        for item in models
        if isinstance(item, dict) and isinstance(item.get("name"), str)
    }
    return sorted(names, key=str.casefold)


def select_candidates(
    candidates: Sequence[Candidate],
    *,
    model: str = "qwen2.5:7b",
    url: str = "http://127.0.0.1:11434",
    timeout: float = 60.0,
    limit: int = 128,
) -> list[int]:
    """Ask Ollama to choose candidate IDs; never accept model-generated bytes."""
    _validate_local_url(url)
    compact = [
        {
            "id": item.id,
            "length": len(item.data),
            "occurrences": item.occurrences,
            "estimated_saving": item.estimated_saving,
            "bytes_base64": base64.b64encode(item.data).decode("ascii"),
        }
        for item in candidates[:256]
    ]
    prompt = (
        "You select repeated binary patterns for a lossless compression dictionary. "
        "Choose candidates that maximize total byte savings while avoiding redundant, "
        "overlapping, or contained patterns. Never invent bytes. Reply with JSON only: "
        '{"selected_ids":[1,2,3]}. Select at most '
        f"{limit} IDs. Candidate dataset:\n" + json.dumps(compact, separators=(",", ":"))
    )
    request_body = json.dumps(
        {"model": model, "prompt": prompt, "stream": False, "format": "json"}
    ).encode("utf-8")
    request = Request(
        url.rstrip("/") + "/api/generate",
        data=request_body,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urlopen(request, timeout=timeout) as response:
            envelope = json.loads(response.read())
        answer = json.loads(envelope.get("response", "{}"))
    except (HTTPError, URLError, TimeoutError, json.JSONDecodeError, OSError) as exc:
        raise OllamaError(f"Ollama request failed: {exc}") from exc

    ids = answer.get("selected_ids")
    if not isinstance(ids, list):
        raise OllamaError("Ollama response did not contain selected_ids")
    allowed = {item.id for item in candidates}
    selected: list[int] = []
    for value in ids:
        if type(value) is int and value in allowed and value not in selected:
            selected.append(value)
        if len(selected) >= limit:
            break
    if not selected and candidates:
        raise OllamaError("Ollama selected no usable candidates")
    return selected
